"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os
import platform

env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] if DEBUG else ['167.233.33.166']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    'users',
    'routes',
    'groups',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'capacitor://localhost',
    'http://localhost',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [     # CSRF (Cross-Site-Request-Forgery) ausschalten, da wir eine Token-basierte Authentifizierung benutzen
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSW'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': env('DEV_DB_NAME'),
            'USER': env('DEV_DB_USER'),
            'PASSWORD': env('DEV_DB_PASSW'),
            'HOST': env('DEV_DB_HOST'),
            'PORT': env('DEV_DB_PORT'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# In deiner settings.py ganz unten
MEDIA_URL = '/'  
MEDIA_ROOT = BASE_DIR  

# Strava Werte aus der .env
from decouple import config
STRAVA_CLIENT_ID     = config('STRAVA_CLIENT_ID')
STRAVA_CLIENT_SECRET = config('STRAVA_CLIENT_SECRET')

# NEU: Diese Liste sagt Django, dass POST-Requests von eurem Frontend sicher sind
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



# AUTOMATISCHER GDAL/GEOS-LOADER FÜR WINDOWS
# Verhindert "ImproperlyConfigured" Fehler bei Teammitgiedern auf Windows.
# Auf Linux/Mac Servern oder Docker wird dieser Block automatisch übersprungen.
# AUTOMATISCHER GDAL/GEOS-LOADER FÜR WINDOWS
if platform.system() == "Windows":
    possible_paths = [
        os.getenv("WINDOWS_GDAL_BIN_PATH"), # 1. Prio: Eigener Pfad aus lokaler .env
        r"C:\Program Files\PostgreSQL\18\bin", # 2. Prio: Postgres 18 (Standard)
        r"C:\Program Files\PostgreSQL\17\bin", # 3. Prio: Fallback für Postgres 17
        r"C:\Program Files\PostgreSQL\16\bin", # 4. Prio: Fallback für Postgres 16
    ]
    
    for path in possible_paths:
        if path and os.path.exists(path):
            os.environ['PATH'] = path + ';' + os.environ['PATH']
            if hasattr(os, 'add_dll_directory'):
                os.add_dll_directory(path)
            
            # Dynamische Erkennung für GDAL und GEOS
            try:
                # 1. GDAL-Pfad setzen
                gdal_files = [f for f in os.listdir(path) if 'gdal' in f.lower() and f.endswith('.dll')]
                if gdal_files:
                    GDAL_LIBRARY_PATH = os.path.join(path, gdal_files[0])
                
                # 2. GEOS-Pfad setzen (sucht nach geos_c.dll oder libgeos_c.dll)
                geos_files = [f for f in os.listdir(path) if 'geos_c' in f.lower() and f.endswith('.dll')]
                if geos_files:
                    GEOS_LIBRARY_PATH = os.path.join(path, geos_files[0])
            except Exception:
                pass
                
            break