# Generated by Django 5.2.9 on 2026-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
