# Generated by Django 5.2.9 on 2026-07-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_membership_unique_user_favorite_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='profilbild',
            field=models.ImageField(blank=True, null=True, upload_to='group_pics/'),
        ),
    ]
