# Generated by Django 5.2.9 on 2026-05-25 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('strecken_id', models.AutoField(primary_key=True, serialize=False)),
                ('strecken_name', models.CharField(max_length=100)),
                ('polyline_map', models.TextField(blank=True, help_text='Google Komprimierungsalgorithmus für Koordinaten', null=True)),
                ('puls_stream', models.JSONField(blank=True, help_text='Array: Pulswerte', null=True)),
                ('zeit_stream', models.JSONField(blank=True, help_text='Array: Zeitstempel für Geschwindigkeitslogik', null=True)),
                ('watt_stream', models.JSONField(blank=True, help_text='Array: Wattwerte', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
