# Generated by Django 5.2.9 on 2026-06-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='group_id',
            field=models.JSONField(blank=True, help_text='Optional: ID der Gruppe, der die Strecke zugeordnet ist', null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='polyline_map',
            field=models.TextField(default='', help_text='Google Komprimierungsalgorithmus für Koordinaten'),
        ),
        migrations.AlterField(
            model_name='route',
            name='zeit_stream',
            field=models.JSONField(default=list, help_text='Array: Zeitstempel für Geschwindigkeitslogik'),
        ),
    ]
