# Generated by Django 5.2.9 on 2026-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='polyline_map',
            field=models.TextField(default='', help_text='Google Komprimierungsalgorithmus für Koordinaten'),
        ),
        migrations.AlterField(
            model_name='route',
            name='zeit_stream',
            field=models.JSONField(help_text='Array: Zeitstempel für Geschwindigkeitslogik'),
        ),
    ]
