# Generated by Django 5.2.9 on 2026-06-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_polyline_map_alter_route_zeit_stream'),
        ('routes', '0002_route_group_id_alter_route_polyline_map_and_more'),
    ]

    operations = [
    ]
