# Generated by Django 5.2.9 on 2026-06-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_merge_20260629_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='zeit_stream',
            field=models.JSONField(default=list, help_text='Array: Zeitstempel für Geschwindigkeitslogik'),
        ),
    ]
