# Generated by Django 5.2.9 on 2026-07-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_merge_20260625_0743'),
        ('routes', '0004_alter_route_zeit_stream'),
    ]

    operations = [
    ]
