# Generated by Django 5.2.9 on 2026-07-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_route_zeit_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='strava_activity_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
