# Generated by Django 5.2.9 on 2026-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_route_zeit_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance_meters',
            field=models.FloatField(default=0, help_text='Gesamtdistanz der Strecke in Metern, berechnet beim Upload'),
        ),
    ]
