# Generated by Django 5.2.9 on 2026-07-05 08:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_membership_unique_user_favorite_group'),
        ('routes', '0005_merge_20260703_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='route',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='GroupRideIntersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersections', to='groups.group')),
            ],
            options={
                'unique_together': {('group', 'date')},
            },
        ),
    ]
