# Generated by Django 5.2.9 on 2026-07-09 19:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_route_end_time_route_geom_route_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprideintersection',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
    ]
