# Generated by Django 5.2.9 on 2026-07-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_route_strava_activity_id'),
        ('routes', '0007_alter_grouprideintersection_geom'),
    ]

    operations = [
    ]
