# Generated by Django 5.2.9 on 2026-07-23 14:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_merge_20260716_1356'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerformanceBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_x', models.IntegerField()),
                ('grid_y', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('puls_sum', models.FloatField(default=0.0)),
                ('puls_count', models.IntegerField(default=0)),
                ('tempo_sum', models.FloatField(default=0.0)),
                ('tempo_count', models.IntegerField(default=0)),
                ('watt_sum', models.FloatField(default=0.0)),
                ('watt_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_buckets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'grid_x', 'grid_y'), name='unique_user_performance_bucket')],
            },
        ),
    ]
