# Generated by Django 5.2.9 on 2026-07-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_merge_20260625_1716'),
        ('routes', '0008_merge_20260715_1152'),
        ('routes', '0009_userperformancebucket'),
    ]

    operations = [
    ]
