# Generated by Django 5.2.9 on 2026-07-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_merge_20260715_1152'),
        ('routes', '0009_userperformancebucket'),
    ]

    operations = [
    ]
