# Generated by Django 5.2.9 on 2026-07-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_route_distance_meters'),
        ('routes', '0010_merge_20260726_2040'),
        ('routes', '0010_merge_20260727_1157'),
        ('routes', '0010_merge_20260727_1210'),
    ]

    operations = [
    ]
