# Generated by Django 5.2.9 on 2026-07-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mail',
        ),
    ]
