# Generated by Django 5.2.9 on 2026-07-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_firstname_userprofile_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_invites_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
