# Generated by Django 5.2.9 on 2026-08-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdevice'),
        ('users', '0007_userprofile_latitude_userprofile_location_name_and_more'),
        ('users', '0008_userprofile_notifications_enabled'),
    ]

    operations = [
    ]
